#!/bin/sh
ARGS=("$@")
DEST=""
while [[ $# -gt 0 ]]; do
  opt="$1"
  shift;
  current_arg="$1"
  case "$opt" in
    "-d"|"--destination"        ) DEST="$1"; shift;;
    # *                   ) echo "ERROR: Invalid option: \""$opt"\"" >&2; exit 1;;
  esac
done
if [ "$DEST" == "" ]
then
  echo "Destination = ."
else
  echo "Destination = $DEST"
fi

set -- "${ARGS[@]}"

for arg in "$@"
do
#echo "$arg"
if [[ (("$arg" != "-d")) && (("$arg" != "$DEST")) ]]
then
TIME=$(stat -f "%Sm" -t "%b %e %H_%M %G" $arg | awk '{print $3;}')
DATE=$(stat -f "%Sm" -t "%b %e %H_%M %G" $arg | awk '{print tolower($1$2);}')
YEAR=$(stat -f "%Sm" -t "%b %e %H_%M %G" $arg | awk '{print $4;}')
BFNAME="$TIME"
BFNAME+="_$DATE"
BFNAME+="_$YEAR"
BFNAME+="_$arg"
#echo "$BFNAME"
  if [[ "$DEST" == "" ]]
  then
    /bin/cp -p -i "$arg" "$BFNAME"
  else
    /bin/cp -p -i "$arg" "$DEST/$BFNAME"
  fi
fi

done