#!/bin/sh
# Sets up a Git user and creates a project repository in the Desktop.
# Designed for use on University of Richmond Macs
read -r -p "Enter your name: " NAME
git config --global user.name "$NAME"
read -r -p "Enter the email associated with your GitHub account: " EMAIL
git config --global user.email "$EMAIL"
git config --global credential.helper cache
echo "Clearing your Desktop \(placing contents in ~/tmpDesktop\)"
mkdir ~/tmpDesktop
for x in ~/Desktop/* ~Desktop/.[!.]* Desktop~/..?*; do
  if [ -e "$x" ]; then mv -- "$x" ~/; fi
done
cd ~
echo "  $ git clone https://github.com/dbrakman/cs322-traffic-proj/ "
git clone https://github.com/dbrakman/cs322-traffic-proj/ Desktop
echo "  $ git checkout -b devel "
git checkout -b devel origin/devel
echo " Use "
echo "  $ git pull origin devel"
echo " to get the latest files from the Web,"
echo " and use the following sequence of commands to put your files online: "
echo "  $ git add file1 file2 ... 
echo "  $ git commit -m 'my commit message' "
echo "  $ git push origin devel "
echo " "
echo " It's important that you add, commit, and push *in that order* "
